<?php

/**
 * @file
 * Variable insertion into twig themes.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * Connecting module to twig theme.
 */
function anzy_theme($existing, $type, $theme, $path) {
  return [
    'Gbook_template' => [
      'variables' => ['form' => [], 'items' => [], 'dest' => ''],
    ],
  ];
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for ajax validation.
 */
function anzy_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'gbook_add_form') {
    $form['system_messages'] = [
      '#markup' => '<div id="form-system-messages"></div>',
      '#weight' => -100,
    ];
    $form['actions']['submit']['#ajax'] = [
      'callback' => 'ajax_submit_handler',
      'event' => 'click',
      'progress' => [
        'type' => 'throbber',
      ],
    ];
  }
}

/**
 * Ajax callback to set messages after submit.
 */
function ajax_submit_handler(array &$form, FormStateInterface $form_state, Request $request) {
  $ajax_response = new AjaxResponse();
  $message = [
    '#theme' => 'status_messages',
    '#message_list' => \Drupal::messenger()->all(),
    '#status_headings' => [
      'status' => t('Status message'),
      'error' => t('Error message'),
      'warning' => t('Warning message'),
    ],
  ];
  $messages = \Drupal::service('renderer')->render($message);
  $ajax_response->addCommand(new HtmlCommand('#form-system-messages', $messages));
  return $ajax_response;
}
